name: Fetch KAMIS API Data and Update CSV

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # requirements.txt에 기록된 패키지 설치

      - name: Fetch KAMIS Data
        env:
          KAMIS_KEY: ${{ secrets.KAMIS_KEY }}
          P_CERT_ID: ${{ secrets.P_CERT_ID }}
        run: |
          python fetch_kamis_data.py

      - name: Convert XML to CSV
        run: |
          python convert_xml_to_csv.py

      - name: Commit and push CSV file
        run: |
          git config --global user.email "heejun1481@jbnu.ac.kr"
          git config --global user.name "aceyang00"
          git add kamis_data.csv
          # 변경 사항이 있을 때만 커밋 및 푸시 수행
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update KAMIS data in CSV format"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
